apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:1.12
      command: ["/bin/sleep"] # DockerのENTRYPOINTに対応
      args: ["3600"] # CMDに対応
